# configmap - deployment - service - horizontal pod autoscalar
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      tier: backend

  template:
    metadata: 
      labels:
        project: roboshop
        component: cart
        tier: backend
    
    spec:
      containers:
      - name: cart
        image: vikasvanamala/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
---
apiVersion: v1
kind: Service

metadata:
  name: cart
  namespace: roboshop

spec:
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
