# configmap - deployment - service - horizontal pod autoscalar
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: 'redis://redis:6379'
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: backend

  template:
    metadata: 
      labels:
        project: roboshop
        component: user
        tier: backend
    
    spec:
      containers:
      - name: user
        image: vikasvanamala/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
---
apiVersion: v1
kind: Service

metadata:
  name: user
  namespace: roboshop

spec:
  selector:
    project: roboshop
    component: user
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
